### ISSUE TITLE
When do you plan to complete BQL schema generator feature

### ISSUE THREAD

**Issue by burakakca** [Blitzapps/blitz-orm#23]
Hi,

When do you plan to complete BQL schema generator feature

**Comment by lveillard** [comment]
Hey! Borm.define() works at the moment to create a typeQL schema from the json BQL schema, but you will probably need to do some tweaks.

However it works on that side BQL => typeQL 

The idea is that in the future you will be able to do BQL => graphQL & BQL => dgraph schema etc

Feel free to share your input schema / issues with the output schema if needed

**Comment by burakakca** [comment]
I thing we need both,

BQL to TypeQL 
and
TypeQL to BQL

**Comment by lveillard** [comment]
BQL is more expressive than typeQL (with exception) and also enforces some
particular patterns to enable the graphQL-like layer. So the task to infer
automatically the BQL schema from a typeQL schema is a bit complicated.

A task that an AI should be able to do tho, by providing for instance the
testSchema.ts and the schema.tql in the /test folder as an example.

Happy to help if you have a particular schema that you would like to build
and test in BQL

**Comment by burakakca** [comment]
I don't have it particular typeQL schema, maybe you can show, how you gonna do that BQL schema from a typeQL schema

**Comment by lveillard** [comment]
> I don't have it particular typeQL schema, maybe you can show, how you gonna do that BQL schema from a typeQL schema

I was proposing do do it manually. if you have a particular use case that you could share, I could build a draft borm schema for the use case so you can see an example.
